# Generated by Django 6.0 on 2025-12-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('couturier', 'Couturier'), ('apprenti', 'Apprenti'), ('contractuel', 'contractuel'), ('commercial', 'Commercial'), ('admin', 'Administratif')], max_length=20)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
