# Generated by Django 6.0 on 2025-12-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_personnel_adresse_personnel_cni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='annees_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='date_fin_contrat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='disponibilites',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='formations_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='jours_conges_restants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='jours_maladies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='jours_travail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='niveau_etude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='notes_competences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='notes_horaires',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='prime_fixe',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='salaire',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='specialites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='statut_emploi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='type_contrat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='type_salaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
