# Generated by Django 6.0 on 2025-12-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_personnel_annees_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='formations_notes',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='notes_competences',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='notes_horaires',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='specialites',
            field=models.CharField(blank=True, null=True),
        ),
    ]
