# Generated by Django 6.0 on 2025-12-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_alter_personnel_formations_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='personnel/'),
        ),
    ]
