# Generated by Django 6.0 on 2025-12-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_personnel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='telephone',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
