# Generated by Django 6.0 on 2025-12-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_alter_personnel_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
