# Generated by Django 6.0 on 2026-01-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_personnel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='actif',
        ),
    ]
