# Generated by Django 6.0 on 2026-01-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tissu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('matiere', models.CharField(choices=[('coton', 'Coton'), ('lin', 'Lin'), ('soie', 'Soie'), ('polyester', 'Polyester'), ('mix', 'Mix')], max_length=20)),
                ('motif', models.CharField(choices=[('unie', 'Unie'), ('rayure', 'Rayure'), ('carreaux', 'Carreaux'), ('floral', 'Floral'), ('autre', 'Autre')], default='unie', max_length=20)),
                ('couleur', models.CharField(blank=True, max_length=50)),
                ('prix_metre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_metres', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tissus/')),
                ('actif', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tissu',
                'verbose_name_plural': 'Tissus',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
