# Generated by Django 6.0 on 2026-01-08 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0001_initial'),
        ('personnel', '0010_personnel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='personnel.personnel', verbose_name='Destinataire'),
        ),
    ]
