# Generated by Django 6.0 on 2026-01-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('difficulte', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], default='moyen', max_length=20)),
                ('type_habit', models.CharField(help_text='Ex: Chemise, Pantalon, Robe...', max_length=50)),
                ('temps_realisation_heures', models.IntegerField(default=4)),
                ('prix_main_oeuvre', models.DecimalField(decimal_places=0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='modeles/')),
                ('description_technique', models.TextField(blank=True, help_text='Détails de confection, mesures...', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modèle',
                'verbose_name_plural': 'Modèles',
                'ordering': ['-date_creation'],
            },
        ),
    ]
