# Generated by Django 6.0 on 2026-01-05 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_typehabit_image'),
        ('modeles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modele',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modele',
            name='type_habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles', to='catalogue.typehabit'),
        ),
    ]
