# Generated by Django 6.0 on 2025-12-24 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('clients', '0002_remove_client_observations_client_genre_client_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mesure', models.DateField(auto_now_add=True)),
                ('tour_poitrine', models.FloatField(blank=True, null=True)),
                ('tour_taille', models.FloatField(blank=True, null=True)),
                ('longueur_manche', models.FloatField(blank=True, null=True)),
                ('longueur_totale', models.FloatField(blank=True, null=True)),
                ('tour_hanche', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='clients.client')),
                ('type_habit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.typehabit')),
            ],
            options={
                'ordering': ['-date_mesure'],
            },
        ),
    ]
