# Generated by Django 6.0 on 2025-12-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesure',
            name='date_prise_mesure',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesure',
            name='hauteur_taille',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesure',
            name='largeur_epaules',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesure',
            name='longueur_bras',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesure',
            name='longueur_epaule',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesure',
            name='longueur_pantalon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesure',
            name='mesureur',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
