# Generated by Django 6.0 on 2026-01-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesures', '0002_mesure_date_prise_mesure_mesure_hauteur_taille_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesure',
            name='tour_hanches',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
