# Generated by Django 6.0 on 2026-01-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesures', '0003_mesure_tour_hanches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesure',
            name='tour_hanches',
        ),
    ]
