# Generated by Django 6.0 on 2026-01-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesures', '0004_remove_mesure_tour_hanches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesure',
            old_name='hauteur_taille',
            new_name='epaule',
        ),
        migrations.RenameField(
            model_name='mesure',
            old_name='largeur_epaules',
            new_name='longueur_dos',
        ),
        migrations.RenameField(
            model_name='mesure',
            old_name='longueur_bras',
            new_name='longueur_jambe',
        ),
        migrations.RenameField(
            model_name='mesure',
            old_name='longueur_epaule',
            new_name='manche_courte',
        ),
        migrations.RenameField(
            model_name='mesure',
            old_name='longueur_manche',
            new_name='manche_longue',
        ),
        migrations.RenameField(
            model_name='mesure',
            old_name='longueur_totale',
            new_name='tour_bras',
        ),
        migrations.AddField(
            model_name='mesure',
            name='tour_cuisse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesure',
            name='tour_mollet',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
