# Generated by Django 6.0 on 2026-01-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesures', '0005_rename_hauteur_taille_mesure_epaule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesure',
            name='date_modification',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='mesure',
            name='encolure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesure',
            name='hauteur_genou',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesure',
            name='hauteur_poitrine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesure',
            name='largeur_dos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesure',
            name='tour_poignet',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
