# Generated by Django 6.0 on 2026-01-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesures', '0006_mesure_date_modification_mesure_encolure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesure',
            name='hauteur_taille',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesure',
            name='largeur_epaule',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesure',
            name='longueur_bras',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesure',
            name='longueur_epaule',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
