# Generated by Django 6.0 on 2025-12-24 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('espece', 'Espèces'), ('carte', 'Carte bancaire'), ('mobile', 'Paiement mobile')], default='espece', max_length=50)),
                ('note', models.TextField(blank=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='commandes.commande')),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
    ]
