# Generated by Django 6.0 on 2025-12-24 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('prevu', 'Prévue'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='prevu', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('instructeur', models.ForeignKey(limit_choices_to={'role': 'couturier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.personnel')),
                ('participants', models.ManyToManyField(blank=True, related_name='formations', to='personnel.personnel')),
            ],
            options={
                'ordering': ['date_debut'],
            },
        ),
    ]
