# Generated by Django 6.0 on 2025-12-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='certification_delivree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formation',
            name='image_couverture',
            field=models.ImageField(blank=True, null=True, upload_to='formations/couvertures/'),
        ),
        migrations.AddField(
            model_name='formation',
            name='materiel_fourni',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formation',
            name='materiel_requis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='nombre_places',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='objectifs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='prix_par_personne',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='repas_inclus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formation',
            name='support_pdf',
            field=models.BooleanField(default=False),
        ),
    ]
