# Generated by Django 6.0 on 2025-12-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_formation_certification_delivree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='duree_heures',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='duree_jours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
