# Generated by Django 6.0 on 2025-12-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_formation_duree_heures_formation_duree_jours'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='formateur',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='formation',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='lieu',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
