# Generated by Django 6.0 on 2025-12-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0004_formation_formateur_formation_heure_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='type_formation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='objectifs',
            field=models.CharField(blank=True),
        ),
    ]
