# Generated by Django 6.0 on 2026-01-05 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0005_formation_type_formation_alter_formation_objectifs'),
        ('personnel', '0008_personnel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='formateur',
        ),
        migrations.AlterField(
            model_name='formation',
            name='instructeur',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.personnel'),
        ),
    ]
