# Generated by Django 6.0 on 2026-01-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0006_remove_formation_formateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='statut',
            field=models.CharField(choices=[('planifiee', 'Planifiée'), ('encours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20),
        ),
    ]
