# Generated by Django 6.0 on 2025-12-24 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_alter_typehabit_options_typehabit_description_and_more'),
        ('clients', '0002_remove_client_observations_client_genre_client_note_and_more'),
        ('mesures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('encours', 'En cours'), ('termine', 'Terminé'), ('livre', 'Livré'), ('annule', 'Annulé')], default='encours', max_length=20)),
                ('prix_total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('avance', models.DecimalField(decimal_places=0, max_digits=10)),
                ('reste_a_payer', models.DecimalField(decimal_places=0, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='clients.client')),
                ('mesure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesures.mesure')),
                ('type_habit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.typehabit')),
            ],
            options={
                'ordering': ['-date_commande'],
            },
        ),
    ]
