# Generated by Django 6.0 on 2025-12-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_alter_commande_avance_alter_commande_prix_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='avance',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
    ]
