# Generated by Django 6.0 on 2025-12-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_alter_commande_avance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='reste_a_payer',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
    ]
