# Generated by Django 6.0 on 2026-01-05 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_typehabit_image'),
        ('commandes', '0004_alter_commande_reste_a_payer'),
        ('modeles', '0002_alter_modele_nom_alter_modele_type_habit'),
        ('tissus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='modele',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modeles.modele'),
        ),
        migrations.AddField(
            model_name='commande',
            name='tissu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tissus.tissu'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='type_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.typehabit'),
        ),
    ]
