# Generated by Django 6.0 on 2026-01-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_commande_modele_commande_tissu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('encours', 'En cours'), ('termine', 'Terminé'), ('en_attente', 'En attente'), ('livre', 'Livré'), ('annule', 'Annulé')], default='encours', max_length=20),
        ),
    ]
