# Generated by Django 6.0 on 2026-01-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_alter_commande_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('encours', 'En cours'), ('termine', 'Terminé'), ('livre', 'Livré'), ('annule', 'Annulé')], default='encours', max_length=20),
        ),
    ]
