# Generated by Django 6.0 on 2026-01-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('nom_atelier', models.CharField(default='Mon Atelier de Couture', max_length=255)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/logos/')),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('tva', models.DecimalField(decimal_places=0, default=0.0, help_text='Taux de TVA en %', max_digits=5)),
                ('delai_confection_standard', models.IntegerField(default=7, help_text='Délai standard en jours')),
                ('seuil_stock_bas', models.IntegerField(default=5, help_text='Alerte stock bas (quantité)')),
            ],
            options={
                'verbose_name': 'Paramètres',
                'verbose_name_plural': 'Paramètres',
            },
        ),
    ]
