# Generated by Django 6.0 on 2026-01-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='langue',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=5),
        ),
        migrations.AddField(
            model_name='setting',
            name='theme',
            field=models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre')], default='light', max_length=10),
        ),
    ]
