# Generated by Django 6.0 on 2025-12-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typehabit',
            options={'ordering': ['nom'], 'verbose_name': "Type d'habit", 'verbose_name_plural': "Types d'habits"},
        ),
        migrations.AddField(
            model_name='typehabit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typehabit',
            name='prix_standard',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
