# Generated by Django 6.0 on 2025-12-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_typehabit_options_typehabit_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typehabit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue/habits/'),
        ),
    ]
