# Generated by Django 6.0 on 2026-01-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_observations_client_genre_client_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/'),
        ),
        migrations.AddField(
            model_name='client',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.CharField(blank=True, help_text='Origine du client (recommandation, Web, publicité, etc.)', max_length=50),
        ),
    ]
